from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.gewijzigde_personen_hal_collection_links import GewijzigdePersonenHalCollectionLinks
from openapi_server import util

from openapi_server.models.gewijzigde_personen_hal_collection_links import GewijzigdePersonenHalCollectionLinks  # noqa: E501

class GewijzigdePersonenHalCollectie(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, links=None, burgerservicenummers=None):  # noqa: E501
        """GewijzigdePersonenHalCollectie - a model defined in OpenAPI

        :param links: The links of this GewijzigdePersonenHalCollectie.  # noqa: E501
        :type links: GewijzigdePersonenHalCollectionLinks
        :param burgerservicenummers: The burgerservicenummers of this GewijzigdePersonenHalCollectie.  # noqa: E501
        :type burgerservicenummers: List[str]
        """
        self.openapi_types = {
            'links': GewijzigdePersonenHalCollectionLinks,
            'burgerservicenummers': List[str]
        }

        self.attribute_map = {
            'links': '_links',
            'burgerservicenummers': 'burgerservicenummers'
        }

        self._links = links
        self._burgerservicenummers = burgerservicenummers

    @classmethod
    def from_dict(cls, dikt) -> 'GewijzigdePersonenHalCollectie':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GewijzigdePersonenHalCollectie of this GewijzigdePersonenHalCollectie.  # noqa: E501
        :rtype: GewijzigdePersonenHalCollectie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> GewijzigdePersonenHalCollectionLinks:
        """Gets the links of this GewijzigdePersonenHalCollectie.


        :return: The links of this GewijzigdePersonenHalCollectie.
        :rtype: GewijzigdePersonenHalCollectionLinks
        """
        return self._links

    @links.setter
    def links(self, links: GewijzigdePersonenHalCollectionLinks):
        """Sets the links of this GewijzigdePersonenHalCollectie.


        :param links: The links of this GewijzigdePersonenHalCollectie.
        :type links: GewijzigdePersonenHalCollectionLinks
        """

        self._links = links

    @property
    def burgerservicenummers(self) -> List[str]:
        """Gets the burgerservicenummers of this GewijzigdePersonenHalCollectie.


        :return: The burgerservicenummers of this GewijzigdePersonenHalCollectie.
        :rtype: List[str]
        """
        return self._burgerservicenummers

    @burgerservicenummers.setter
    def burgerservicenummers(self, burgerservicenummers: List[str]):
        """Sets the burgerservicenummers of this GewijzigdePersonenHalCollectie.


        :param burgerservicenummers: The burgerservicenummers of this GewijzigdePersonenHalCollectie.
        :type burgerservicenummers: List[str]
        """

        self._burgerservicenummers = burgerservicenummers
