from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Volgindicatie(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, einddatum=None):  # noqa: E501
        """Volgindicatie - a model defined in OpenAPI

        :param einddatum: The einddatum of this Volgindicatie.  # noqa: E501
        :type einddatum: date
        """
        self.openapi_types = {
            'einddatum': date
        }

        self.attribute_map = {
            'einddatum': 'einddatum'
        }

        self._einddatum = einddatum

    @classmethod
    def from_dict(cls, dikt) -> 'Volgindicatie':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Volgindicatie of this Volgindicatie.  # noqa: E501
        :rtype: Volgindicatie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def einddatum(self) -> date:
        """Gets the einddatum of this Volgindicatie.

        Datum vanaf wanneer de volgindicatie niet meer actief zal zijn.  # noqa: E501

        :return: The einddatum of this Volgindicatie.
        :rtype: date
        """
        return self._einddatum

    @einddatum.setter
    def einddatum(self, einddatum: date):
        """Sets the einddatum of this Volgindicatie.

        Datum vanaf wanneer de volgindicatie niet meer actief zal zijn.  # noqa: E501

        :param einddatum: The einddatum of this Volgindicatie.
        :type einddatum: date
        """

        self._einddatum = einddatum
