from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VolgindicatieRaadplegen(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, einddatum=None, begindatum=None, burgerservicenummer=None):  # noqa: E501
        """VolgindicatieRaadplegen - a model defined in OpenAPI

        :param einddatum: The einddatum of this VolgindicatieRaadplegen.  # noqa: E501
        :type einddatum: date
        :param begindatum: The begindatum of this VolgindicatieRaadplegen.  # noqa: E501
        :type begindatum: date
        :param burgerservicenummer: The burgerservicenummer of this VolgindicatieRaadplegen.  # noqa: E501
        :type burgerservicenummer: str
        """
        self.openapi_types = {
            'einddatum': date,
            'begindatum': date,
            'burgerservicenummer': str
        }

        self.attribute_map = {
            'einddatum': 'einddatum',
            'begindatum': 'begindatum',
            'burgerservicenummer': 'burgerservicenummer'
        }

        self._einddatum = einddatum
        self._begindatum = begindatum
        self._burgerservicenummer = burgerservicenummer

    @classmethod
    def from_dict(cls, dikt) -> 'VolgindicatieRaadplegen':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VolgindicatieRaadplegen of this VolgindicatieRaadplegen.  # noqa: E501
        :rtype: VolgindicatieRaadplegen
        """
        return util.deserialize_model(dikt, cls)

    @property
    def einddatum(self) -> date:
        """Gets the einddatum of this VolgindicatieRaadplegen.

        Datum vanaf wanneer de volgindicatie niet meer actief zal zijn.  # noqa: E501

        :return: The einddatum of this VolgindicatieRaadplegen.
        :rtype: date
        """
        return self._einddatum

    @einddatum.setter
    def einddatum(self, einddatum: date):
        """Sets the einddatum of this VolgindicatieRaadplegen.

        Datum vanaf wanneer de volgindicatie niet meer actief zal zijn.  # noqa: E501

        :param einddatum: The einddatum of this VolgindicatieRaadplegen.
        :type einddatum: date
        """

        self._einddatum = einddatum

    @property
    def begindatum(self) -> date:
        """Gets the begindatum of this VolgindicatieRaadplegen.

        Datum sinds wanneer de volgindicatie actief is.  # noqa: E501

        :return: The begindatum of this VolgindicatieRaadplegen.
        :rtype: date
        """
        return self._begindatum

    @begindatum.setter
    def begindatum(self, begindatum: date):
        """Sets the begindatum of this VolgindicatieRaadplegen.

        Datum sinds wanneer de volgindicatie actief is.  # noqa: E501

        :param begindatum: The begindatum of this VolgindicatieRaadplegen.
        :type begindatum: date
        """

        self._begindatum = begindatum

    @property
    def burgerservicenummer(self) -> str:
        """Gets the burgerservicenummer of this VolgindicatieRaadplegen.

        Identificerend gegeven van een ingeschreven natuurlijk persoon, als bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.  # noqa: E501

        :return: The burgerservicenummer of this VolgindicatieRaadplegen.
        :rtype: str
        """
        return self._burgerservicenummer

    @burgerservicenummer.setter
    def burgerservicenummer(self, burgerservicenummer: str):
        """Sets the burgerservicenummer of this VolgindicatieRaadplegen.

        Identificerend gegeven van een ingeschreven natuurlijk persoon, als bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.  # noqa: E501

        :param burgerservicenummer: The burgerservicenummer of this VolgindicatieRaadplegen.
        :type burgerservicenummer: str
        """

        self._burgerservicenummer = burgerservicenummer
